
name: "Terraform"

on:
  push:
    branches:
      - main

env:
  TERRAFORM_VERSION: 0.14.2
  TERRAGRUNT_VERSION: v0.29.2

jobs:
  terragrunt-apply-all-staging:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ca-central-1
      TF_VAR_metrics_token: ${{ secrets.STAGING_METRICS_TOKEN }}
      TF_VAR_route53_zone_name: ${{ secrets.STAGING_ROUTE53_ZONE_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Setup Terragrunt
        run: |
          mkdir bin
          wget -O bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/$TERRAGRUNT_VERSION/terragrunt_linux_amd64
          chmod +x bin/terragrunt
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Apply All staging
        run: |
          cd env/staging
          terragrunt run-all apply --terragrunt-non-interactive