name: "Lint"

on:
  pull_request:
    paths:
      - "env/**"
      - ".github/workflows/**"

env:
  OPA_VERSION: v0.28.0
  TERRAFORM_VERSION: 0.14.2
  TERRAGRUNT_VERSION: v0.29.2

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ca-central-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Setup Terragrunt and OPA
        run: |
          mkdir bin
          wget -O bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/$TERRAGRUNT_VERSION/terragrunt_linux_amd64
          wget -O bin/opa https://github.com/open-policy-agent/opa/releases/download/$OPA_VERSION/opa_linux_amd64
          chmod +x bin/*
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Lint HCL files
        run: |
          cd env
          terragrunt hclfmt --terragrunt-check

      - name: Lint Rego files
        run: |
          cd .github/workflows/policy
          opa check *.rego

      - name: Check prod Terragrunt uses tagged modules
        run: .github/workflows/scripts/check-terragrunt-tagged.sh env/production