name: "Lint"

on:
  pull_request:
    paths:
      - "env/**"
      - ".github/workflows/**"

env:
  SCRIPTS: ./.github/workflows/scripts

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ca-central-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Environment Variables
        run: |
          ${{ env.SCRIPTS }}/setenv.sh TERRAFORM_VERSION >> $GITHUB_ENV
          ${{ env.SCRIPTS }}/setenv.sh TERRAGRUNT_VERSION >> $GITHUB_EN
          ${{ env.SCRIPTS }}/setenv.sh OPA_VERSION >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Setup Terragrunt and OPA
        run: |
          ${{ env.SCRIPTS }}/setup_tg_opa.sh
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Lint HCL files
        run: |
          cd env
          terragrunt hclfmt --terragrunt-check

      - name: Lint Rego files
        run: |
          cd .github/workflows/policy
          opa check *.rego