name: "Security scan"

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "aws/**"
      - "env/common/**"
      - ".github/workflows/**"

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkov security scan
        id: checkov
        uses: bridgecrewio/checkov-action@6693d5f2dc45ab72428fcdb20e38b7fd14c8df50 #master as of Jun 10
        with:
          directory: .
          framework: terraform
          output_format: cli
          download_external_modules: true
